name: 'Terraform infrastructure deployment to Azure cloud'


on:
  push:
    branches: [ "main" ]


jobs:
  terraform:
    name: 'TerraformAzuecloud'
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    environment: testing


    defaults:
      run:
        shell: bash

    steps:
    - uses: act10ns/slack@v2
      with:
          status: started deployment
          channel: '#github-actions-pipeline-notification'
          message: Started terraform deployment to Azure cloud..
      if: always()

    - name: Checkout
      uses: actions/checkout@v4

    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


    - name: Terraform Init
      run: terraform init


    - name: Terraform Plan
      run: terraform plan -input=false


    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
